### ISSUE TITLE
Simplify the image

### ISSUE THREAD

**Issue by bast** [dev-cafe/branching-model#17]
Perhaps split into two images. I will probably have a go at it.

**Comment by robertodr** [comment]
It would be nice to have something that looks more "standard", meaning like the pictures on the Git book.

**Comment by bast** [comment]
What do you think about this: https://github.com/bast/branching-model/blob/gh-pages/img/branches.jpg?

**Comment by bast** [comment]
One change I want to make ASAP there is to add fork branches and label them red. Also the "feature" branch to make it more clear that these branches live on the fork.

**Comment by robertodr** [comment]
Looks good! How did you make it? I would rotate the trees 90° clockwise, so that they are horizontal, not vertical. Also, the branch names look like tags (though they have a different shading) which might be confusing.

**Comment by bast** [comment]
OK I will rotate. This is also Inkscape. My intention was to make tags look like branches because they are conceptually not so different. I really want the branch names to point to a specific commit. How should I distinguish them?

**Comment by robertodr** [comment]
I see your point and it's actually helpful to have a visual code that "demystifies" the use of tags. So, scrap my previous comment and keep branch names as they are.

**Comment by bast** [comment]
New suggestion: http://bast.github.io/branching-model/

**Comment by robertodr** [comment]
Looks good! The vertical distance between branches can possibly be reduced to make it even more compact.

**Comment by bast** [comment]
I will submit it as PR. We can always tweak it further later.

**Comment by robertodr** [comment]
Sure thing! :wink:
