### ISSUE TITLE
Consider porting the document to Jekyll/gh-pages like the Semantic Versioning page

### ISSUE THREAD

**Issue by bast** [dev-cafe/branching-model#5]
We don't have to do it now but as soon as things converge. Could be nicer to expose a website instead of a readme.

**Comment by bast** [comment]
@robertodr I have ported this to gh-pages, see http://bast.fr/branching-model/. Is it OK if I nuke master and replace by this gh-pages? Bonus is that we serve svg directly and don't have to track the png image anymore.

**Comment by robertodr** [comment]
No problem for me. Can't we serve it under the dev-cafe blog?

**Comment by bast** [comment]
We could serve it under the blog but my thought was that perhaps teams might eventually want to fork it and adapt it and then they perhaps don't want to fork the whole blog site.

**Comment by robertodr** [comment]
Good point, but can you point the generated webpage to show on the blog instead of on your personal website?

**Comment by bast** [comment]
Oh yeah - the personal website is just for demo and will be gone after this issue is solved. It will end up on https://dev-cafe.github.io/branching-model/ or https://dev-cafe.github.io/semantic-branching-model/.

**Comment by bast** [comment]
Done.

**Comment by robertodr** [comment]
It doesn't appear under "Posts" nor there's a link to it from the blog home.
